// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OzFoJ39fNNbGVQufJ3MTTUTWFh1TgmY',
    appId: '1:1021674468700:android:cf51d73f84330351b0fd99',
    messagingSenderId: '1021674468700',
    projectId: 'pc-api-8142476895956216413-226',
    storageBucket: 'pc-api-8142476895956216413-226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYm9F98enTjliLZbZAbQjEg5VPSHQd2Hs',
    appId: '1:1021674468700:ios:259daa7bcb40627bb0fd99',
    messagingSenderId: '1021674468700',
    projectId: 'pc-api-8142476895956216413-226',
    storageBucket: 'pc-api-8142476895956216413-226.appspot.com',
    iosClientId: '1021674468700-h2n4nb8ps6ife0tnn4olcrgbis71i2bv.apps.googleusercontent.com',
    iosBundleId: 'com.novizco.qktrade',
  );
}
